#!/bin/csh
# invoke transport <name> where <>.dat is the input deck
if ( ! $?TRANSPORT_DIR ) then
    setenv TRANSPORT_DIR ..
endif
setenv TRANSPORT_BIN_DIR $TRANSPORT_DIR/bin

$TRANSPORT_BIN_DIR/trns.exe < trns.dat > trns.out
#
if (-f fort.7) then
mv -f fort.7 trns.bin
endif
#
if (-f fort.8) then
mv -f fort.8 trns.plot
endif
